services:
  - type: web
    name: saanvi-ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app --bind 0.0.0.0:8000 --workers 4 --threads 2 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: run  # Use the correct entry point file (run.py)
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_BASE_URL
        value: https://models.inference.ai.azure.com
      - key: OPENAI_MODEL
        value: gpt-4o
      - key: EMBEDDING_MODEL
        value: text-embedding-3-large
      - key: MAX_FILE_SIZE
        value: 104857600
      - key: RATE_LIMIT_WINDOW
        value: 60
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 3
      - key: PINECONE_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: PINECONE_ENVIRONMENT
        sync: false
      - key: PINECONE_INDEX_NAME
        value: saanvi-production
      - key: LLM_TYPE
        value: google
      - key: EMBEDDING_TYPE
        value: google
      - key: PINECONE_HOST
        value: https://saanvi-uun6jyc.svc.aped-4627-b74a.pinecone.io
      - key: CORS_ORIGINS
        value: http://localhost:3000
