# render.yaml
services:
  - type: web
    name: saanvi-ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app --bind 0.0.0.0:$PORT --workers 4 --threads 2 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
      - key: FLASK_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: PINECONE_ENVIRONMENT
        sync: false
      - key: PINECONE_INDEX_NAME
        value: saanvi-production
      - key: MAX_FILE_SIZE
        value: 104857600
      - key: RATE_LIMIT_WINDOW
        value: 60
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 3